apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
      nodePort: 30034
